const fs = require('fs');
const path = require('path');

// --- Configuration ---
const MUSIC_DIR = path.join(__dirname, 'src', 'music');
const OUTPUT_FILE = path.join(__dirname, 'src', 'musicMap.js');

// Map directory names to OpenWeatherMap 'main' condition
const WEATHER_MAPPING = {
    'sunny': ['Clear'],
    'rainy': ['Rain', 'Drizzle', 'Thunderstorm', 'Mist'], // Move Thunderstorm to stormy when supported
    'snowy': ['Snow'],
    'cloudy': ['Clouds'],
    'minesweeper': ['Minesweeper'] // Easter egg
    // Not currently supported:
    // 'hazy': ['Haze', 'Fog']
    // 'smoky': ['Smoke', 'Ash']
    // 'sandy': ['Sand', 'Dust']
    // 'stormy': ['Thunderstorm', 'Squall', 'Tornado']
};

// --- Script Logic ---

function generateMusicMap() {
    console.log('Generating music map...');

    // 1. Traverse Music Directory
    let musicData = {};

    try {
        const weatherFolders = fs.readdirSync(MUSIC_DIR, { withFileTypes: true })
            .filter(dirent => dirent.isDirectory())
            .map(dirent => dirent.name);
        
        // 2. Map Files to Folders
        for (const folder of weatherFolders) {
            const folderPath = path.join(MUSIC_DIR, folder);
            const files = fs.readdirSync(folderPath)
                .filter(file => file.endsWith('.mp3') || file.endsWith('.wav')); // Filter for audio files

            if (files.length > 0) {
                // Construct the import path relative to the final Music.js file location
                const relativePath = files.map(file => {
                    // This generates the string that will be used for dynamic imports
                    return `./music/${folder}/${file}`;
                });
                
                musicData[folder] = relativePath;
            }
        }
    } catch (error) {
        console.error(`Error reading music directory (${MUSIC_DIR}):`, error.message);
        console.log("Please ensure the directory structure exists: src/Music/[Sunny|Rainy|Cloudy]/...");
        return;
    }


    // 3. Generate Final JavaScript Content
    let fileContent = `// This file is auto-generated by generateMusicMap.js. DO NOT EDIT MANUALLY.\n\n`;
    
    // a. Write the Dynamic Imports and Library Definition
    fileContent += `const MUSIC_LIBRARY = {\n`;
    
    // b. Map OpenWeather keys to the imported arrays
    for (const [folder, owmKeys] of Object.entries(WEATHER_MAPPING)) {
        if (musicData[folder] && musicData[folder].length > 0) {
            const tracksList = musicData[folder].map(p => `require('${p}')`).join(', ');
            
            for (const key of owmKeys) {
                // Each OpenWeather key gets an array of required tracks
                fileContent += `  '${key}': [${tracksList}],\n`;
            }
        } else {
            console.warn(`Warning: No audio files found in Music/${folder}.`);
        }
    }
    
    // c. Add Default
    if (musicData['minesweeper'] && musicData['minesweeper'].length > 0) {
        const defaultTracks = musicData['minesweeper'].map(p => `require('${p}')`).join(', ');
        fileContent += `  'default': [${defaultTracks}], // Fallback to Minesweeper\n`;
    } else {
        fileContent += `  'default': [],\n`;
    }

    fileContent += `};\n\n`;
    fileContent += `export default MUSIC_LIBRARY;\n`;


    // 4. Write the File
    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Music map successfully written to ${path.relative(__dirname, OUTPUT_FILE)}`);
}

generateMusicMap();